In [1]:
# import packages
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree
from sklearn.metrics import classification_report
from sklearn import preprocessing

In [30]:
# load dataset:
data = pd.read_csv(r'E:\ExcelR ass\Decision_tree_ass\Company_Data.csv')
data.head()

Sales  CompPrice  Income  Advertising  Population  Price ShelveLoc  Age  \
0   9.50        138      73           11         276    120       Bad   42   
1  11.22        111      48           16         260     83      Good   65   
2  10.06        113      35           10         269     80    Medium   59   
3   7.40        117     100            4         466     97    Medium   55   
4   4.15        141      64            3         340    128       Bad   38   

   Education Urban   US  
0         17   Yes  Yes  
1         10   Yes  Yes  
2         12   Yes  Yes  
3         14   Yes  Yes  
4         13   Yes   No

In [31]:
# Using 2 Categories :
# split data :
import numpy as np
data_dummy = pd.get_dummies(data)
data_dummy["sales_nature"] = pd.cut(data["Sales"], bins = [-1,7.5,16.27], labels = ["Risky", "Good"])
x = data_dummy.iloc[:,1:15]
y = data_dummy.iloc[:,-1]
# data.head()
# data.shape    # (400, 21)
# print(y.isnull().sum())
# data_dummy.head()
# data_dummy.shape   # (400, 16)
data_dummy["sales_nature"] = data_dummy["sales_nature"].replace(np.NaN, 0)
# data_dummy["sales_nature"] = data_dummy["sales_nature"].fillna("Moderate")
data_dummy.isnull().sum()
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=7)

In [33]:
# C5.0 :
model = DecisionTreeClassifier(criterion='entropy')
model.fit(x_train, y_train)
y_pred = model.predict(x_test)
y_pred
np.mean(y_pred == y_test)  # 73.75 %

0.725

In [34]:
# CART :
model = DecisionTreeClassifier(criterion='gini')
model.fit(x_train, y_train)
y_pred = model.predict(x_test)
y_pred
np.mean(y_pred == y_test)  # 68.75 %

0.6625

In [35]:
# Random Forest :
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import KFold, cross_val_score
kfold = KFold(n_splits=10, random_state=7)
model = RandomForestClassifier(n_estimators=100, max_features = 3)
result = cross_val_score(model, x, y, cv=kfold)
result

C:\Users\mites\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:293: FutureWarning: Setting a random_state has no effect since shuffle is False. This will raise an error in 0.24. You should leave random_state to its default (None), or set shuffle=True.
  warnings.warn(


array([0.775, 0.9  , 0.65 , 0.825, 0.725, 0.9  , 0.825, 0.85 , 0.8  ,
       0.825])

In [36]:
print(result.mean())        # 82.25% 

0.8074999999999999


In [37]:
# Bagging for Company_data :
from sklearn.ensemble import BaggingClassifier
cart = DecisionTreeClassifier()
model = BaggingClassifier(base_estimator = cart, n_estimators = 100, random_state = 7)
results = cross_val_score(model, x, y, cv=kfold)
results

array([0.85 , 0.875, 0.725, 0.875, 0.8  , 0.875, 0.775, 0.75 , 0.725,
       0.875])

In [38]:
results.mean()            # around 81.25% accuracy using Baggingclassifier

0.8125

In [16]:
# Fraud_ Check :
# load dataset:
data = pd.read_csv(r'E:\ExcelR ass\Decision_tree_ass\Fraud_check.csv')
data.head()

Undergrad Marital.Status  Taxable.Income  City.Population  Work.Experience  \
0        NO         Single           68833            50047               10   
1       YES       Divorced           33700           134075               18   
2        NO        Married           36925           160205               30   
3       YES         Single           50190           193264               15   
4        NO        Married           81002            27533               28   

  Urban  
0   YES  
1   YES  
2   YES  
3   YES  
4    NO

In [17]:
# reanme columns names  :
data.columns = ["Undergrad", "Marital_status", "tax_income", "population", "work_exp", "Urban"]
data.head()
data["tax_income"].describe()

count      600.000000
mean     55208.375000
std      26204.827597
min      10003.000000
25%      32871.500000
50%      55074.500000
75%      78611.750000
max      99619.000000
Name: tax_income, dtype: float64

In [18]:
df = pd.get_dummies(data)
df["tax_nature"] = pd.cut(data["tax_income"], bins=[10000,30000,99619], labels=["Risky","Good"])
df.head()
# df.shape     #(600, 11)

tax_income  population  work_exp  Undergrad_NO  Undergrad_YES  \
0       68833       50047        10             1              0   
1       33700      134075        18             0              1   
2       36925      160205        30             1              0   
3       50190      193264        15             0              1   
4       81002       27533        28             1              0   

   Marital_status_Divorced  Marital_status_Married  Marital_status_Single  \
0                        0                       0                      1   
1                        1                       0                      0   
2                        0                       1                      0   
3                        0                       0                      1   
4                        0                       1                      0   

   Urban_NO  Urban_YES tax_nature  
0         0          1       Good  
1         0          1       Good  
2         0          1       Good  
3         0          1       Good  
4         1          0       Good

In [19]:
x = df.iloc[:,0:10]
y = df.iloc[:,-1]
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2)


In [20]:
# Random Forest :
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import KFold, cross_val_score
kfold = KFold(n_splits=10, random_state=7)
model = RandomForestClassifier(n_estimators=100, max_features = 2)
result = cross_val_score(model, x, y, cv=kfold)
result

C:\Users\mites\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:293: FutureWarning: Setting a random_state has no effect since shuffle is False. This will raise an error in 0.24. You should leave random_state to its default (None), or set shuffle=True.
  warnings.warn(


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [23]:
result.mean()
# Here, using Random Forest we are getting 100 % accuracy which can lead to overfittinf problem.

1.0

In [28]:
# Bagging for Fraud check :
from sklearn.ensemble import BaggingClassifier
cart = DecisionTreeClassifier()
model = BaggingClassifier(base_estimator = cart, n_estimators = 100, random_state = 7)
results = cross_val_score(model, x, y, cv=kfold)
results

array([1.        , 1.        , 1.        , 1.        , 0.98333333,
       1.        , 1.        , 1.        , 1.        , 1.        ])

In [29]:
results.mean()             # around 99.83 % accuracy using BaggingClassifier

0.9983333333333334